version: 0.1
phases:
  install:
    commands:
      - sudo pip install --upgrade awscli
      - aws --version
      - sudo pip install 'chalice>=1.18.0,<1.19.0'
      - sudo pip install -r requirements.txt
      - chalice deploy --stage stg
artifacts:
  type: zip
  files:
    - transformed.yaml
